services:
  neo4j-history:
    hostname: neo4j-history
    image: neo4j:2025.07.1
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/w4gfe57GDF325hfw
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
    depends_on:
      - neo4j-migrations
#    volumes:
#      - neo4j_data:/data
#      - neo4j_logs:/logs
#      - neo4j_import:/var/lib/neo4j/import
#      - neo4j_plugins:/plugins
#    networks:
#      - historygraph
  
  neo4j-migrations:
    hostname: neo4j-migrations
    image: neo4j:2025.07.1
    ports:
      - "7475:7474"  # HTTP
      - "7688:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/w4gfe57GDF325hfw
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
  #    volumes:
  #      - neo4j_data:/data
  #      - neo4j_logs:/logs
  #      - neo4j_import:/var/lib/neo4j/import
  #      - neo4j_plugins:/plugins
  #    networks:
  #      - historygraph

  webapi:
    image: historygraph-webapi:0.0.1
    build:
      dockerfile: ./WebApi/Dockerfile
    ports:
      - "6513:80"
    environment:
      - NEO4J__HISTORY__URI=bolt://neo4j-history:7687
      - NEO4J__HISTORY__USER=neo4j
      - NEO4J__HISTORY__PASSWORD=w4gfe57GDF325hfw
      - NEO4J__MIGRATIONS__URI=bolt://neo4j-migrations:7687
      - NEO4J__MIGRATIONS__USER=neo4j
      - NEO4J__MIGRATIONS__PASSWORD=w4gfe57GDF325hfw
      - ASPNETCORE_URLS=http://*:80
    #depends_on:
    #  - neo4j
    #networks:
    #  - historygraph
